// src/lib/motivation.ts

export const motivationalQuotes = [
  "Believe you can and you're halfway there.",
  "The secret of getting ahead is getting started.",
  "Don't watch the clock; do what it does. Keep going.",
  "The expert in anything was once a beginner.",
  "The only way to do great work is to love what you do.",
  "Success is the sum of small efforts, repeated day in and day out.",
  "Push yourself, because no one else is going to do it for you.",
  "Every accomplishment starts with the decision to try.",
  "The harder you work, the greater you'll feel when you achieve it.",
  "Dream bigger. Do bigger.",
  "Your only limit is your mind.",
  "The future belongs to those who believe in the beauty of their dreams.",
  "You are capable of more than you know.",
  "The journey of a thousand miles begins with a single step.",
  "Embrace the challenges. They make you stronger.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
  "What you get by achieving your goals is not as important as what you become by achieving your goals.",
  "Act as if what you do makes a difference. It does.",
  "The most effective way to do it, is to do it.",
  "Strive for progress, not perfection.",
  "The key to success is to focus on goals, not obstacles.",
  "You have to be at your strongest when you’re feeling at your weakest.",
  "The pain you feel today will be the strength you feel tomorrow.",
  "It’s not whether you get knocked down, it’s whether you get up.",
  "Failure is the opportunity to begin again more intelligently.",
  "Our greatest glory is not in never falling, but in rising every time we fall.",
  "If you can dream it, you can do it.",
  "A little progress each day adds up to big results.",
  "The best way to predict the future is to create it.",
  "You are the only one who can limit your greatness.",
  "Make each day your masterpiece.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Your positive action combined with positive thinking results in success.",
  "The will to win, the desire to succeed, the urge to reach your full potential... these are the keys that will unlock the door to personal excellence.",
  "Do not wait to strike till the iron is hot; but make it hot by striking.",
  "Whether you think you can or you think you can’t, you’re right.",
  "I am not a product of my circumstances. I am a product of my decisions.",
  "The mind is everything. What you think you become.",
  "An unexamined life is not worth living.",
  "Eighty percent of success is showing up.",
  "Winning isn’t everything, but wanting to win is.",
  "I’ve missed more than 9000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.",
  "The only person you are destined to become is the person you decide to be.",
  "Go confidently in the direction of your dreams. Live the life you’ve imagined.",
  "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.",
  "The most common way people give up their power is by thinking they don’t have any.",
  "The mind is the limit. As long as the mind can envision the fact that you can do something, you can do it, as long as you really believe 100 percent.",
  "What we think, we become.",
  "I have not failed. I’ve just found 10,000 ways that won’t work.",
  "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.",
  "Your time is limited, don’t waste it living someone else’s life.",
  "The best revenge is massive success.",
  "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.",
  "All our dreams can come true if we have the courage to pursue them.",
  "It does not matter how slowly you go as long as you do not stop.",
  "Everything you’ve ever wanted is on the other side of fear.",
  "Hardships often prepare ordinary people for an extraordinary destiny.",
  "The only impossible journey is the one you never begin.",
  "In the middle of every difficulty lies opportunity.",
  "It always seems impossible until it's done.",
  "The secret to getting ahead is getting started.",
  "I am the master of my fate, I am the captain of my soul.",
  "The future depends on what you do today.",
  "Don't let yesterday take up too much of today.",
  "You learn more from failure than from success. Don’t let it stop you. Failure builds character.",
  "The man who has confidence in himself gains the confidence of others.",
  "Creativity is intelligence having fun.",
  "What you lack in talent can be made up with desire, hustle and giving 110% all the time.",
  "Do one thing every day that scares you.",
  "The purpose of our lives is to be happy.",
  "You must do the things you think you cannot do.",
  "If you want to lift yourself up, lift up someone else.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "To live a creative life, we must lose our fear of being wrong.",
  "I would rather die of passion than of boredom.",
  "Whatever you are, be a good one.",
  "If you can't explain it simply, you don't understand it well enough.",
  "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
  "The only thing standing between you and your goal is the bullshit story you keep telling yourself as to why you can't achieve it.",
  "You don't have to be great to start, but you have to start to be great.",
  "The successful warrior is the average man, with laser-like focus.",
  "Perfection is not attainable, but if we chase perfection we can catch excellence.",
  "The power of imagination makes us infinite.",
  "Try not to become a person of success, but rather try to become a person of value.",
  "A creative man is motivated by the desire to achieve, not by the desire to beat others.",
  "A person who never made a mistake never tried anything new.",
  "It is never too late to be what you might have been.",
  "If you are not willing to risk the usual, you will have to settle for the ordinary.",
  "Trust because you are willing to accept the risk, not because it's safe or certain.",
  "All progress takes place outside the comfort zone.",
  "People who are crazy enough to think they can change the world, are the ones who do.",
  "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
  "A journey of a thousand miles begins with a single step.",
  "You can't use up creativity. The more you use, the more you have.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "I find that the harder I work, the more luck I seem to have.",
  "The only place where success comes before work is in the dictionary.",
  "Don’t be afraid to give up the good to go for the great.",
  "There is no substitute for hard work.",
  "You miss 100% of the shots you don’t take.",
  "The best way to appreciate your job is to imagine yourself without one."
];


export const motivationalMessages = [
  "Fantastic effort! Every step forward is a victory.",
  "You've unlocked a new level of awesome. Keep it up!",
  "Achievement unlocked! You're on fire.",
  "That's how it's done! Your dedication is paying off.",
  "Goal smashed! Take a moment to be proud of yourself.",
  "Incredible work! You're making serious progress.",
  "Another milestone reached. You're unstoppable!",
  "Your consistency is key. Well done on another achievement!",
  "You've earned this! Your hard work is showing.",
  "Boom! Another goal down. What's next?",
  "This is what success looks like. Keep building on it.",
  "You're turning your dreams into plans. Amazing!",
  "Look at you go! Your focus is inspiring.",
  "That's a win! Celebrate this moment.",
  "You're building momentum. Nothing can stop you now.",
  "Hard work pays off. This achievement is proof.",
  "You're not just working hard, you're working smart. Bravo!",
  "Another one bites the dust! Great job.",
  "You've just leveled up your skills. Congrats!",
  "This is the result of your dedication. Be proud.",
  "Success! You're making things happen.",
  "You've proven once again that you have what it takes.",
  "Keep this energy going. You're on the right track.",
  "Excellent work! Your progress is remarkable.",
  "You set a goal and you crushed it. Pure excellence.",
  "Your commitment to your goals is inspiring to see.",
  "Another step closer to your dream. Keep climbing.",
  "This is what happens when talent meets hard work. Well done!",
  "You're in the zone! Keep up the fantastic work.",
  "Consider that goal conquered. On to the next challenge!",
  "Your discipline is shining through. Great job.",
  "This is a testament to your perseverance. Don't ever forget it.",
  "You're a star! This achievement is well-deserved.",
  "The results are in: you're awesome.",
  "You're making incredible strides. Keep it up!",
  "Another goal achieved. Your future self is thanking you.",
  "This is the kind of progress that leads to greatness.",
  "You're a productivity powerhouse! Amazing job.",
  "That's a huge win! Your efforts are compounding.",
  "You're building a legacy of success, one achievement at a time.",
  "Outstanding! You've raised the bar.",
  "Your focus and determination are a winning combination.",
  "You've just made a significant leap forward. Celebrate it!",
  "This is the reward for your consistent effort. Enjoy it.",
  "You're on a roll! Keep the streak alive.",
  "Another brilliant accomplishment. You should be very proud.",
  "This is what happens when you refuse to give up. Inspiring!",
  "You're making your vision a reality. Keep going.",
  "That's a major accomplishment. Pat yourself on the back.",
  "You're a true champion. This is just another victory.",
  "Your dedication is the foundation of your success. Solid work.",
  "You're not just meeting expectations, you're exceeding them.",
  "This achievement is a stepping stone to even greater things.",
  "You've just proven that anything is possible with focus.",
  "Your hard work is creating a ripple effect of success.",
  "That's a wrap on another goal. You're doing amazing.",
  "You're a force to be reckoned with. Keep pushing boundaries.",
  "This is the result of your unwavering commitment. Fantastic.",
  "You're a goal-getter! Another one down.",
  "Your progress is a beacon of inspiration. Shine on!",
  "You've turned a challenge into an achievement. That's power.",
  "This is a victory lap moment. Enjoy the feeling of accomplishment.",
  "Your persistence has paid off handsomely. Well done.",
  "You're writing your own success story, one achievement at a time.",
  "This is what excellence in action looks like.",
  "You're not just chasing your dreams, you're catching them.",
  "Another goal in the bag. Your focus is laser-sharp.",
  "You're making big moves. This is just the beginning.",
  "Your effort is the currency of your success. You're rich!",
  "This is a moment to remember. You earned it.",
  "You're building a monument to your dedication. Keep adding bricks.",
  "That's a masterclass in how to achieve a goal. Bravo!",
  "You're a powerhouse of productivity and passion.",
  "This achievement is a clear sign of your growth. Keep evolving.",
  "You've just demonstrated the power of a determined mind.",
  "Your focus is your superpower. Look what you've accomplished!",
  "Another goal down, another level of confidence gained.",
  "You're not just working, you're crafting your future.",
  "This is what happens when you combine vision with action.",
  "Your success is inevitable with this kind of effort.",
  "You're a shining example of what's possible.",
  "This is a huge step forward on your path to success.",
  "You're a problem-solver and a goal-achiever. What a combo!",
  "Your consistency is building a bridge to your dreams.",
  "You've just added another trophy to your collection. Congrats!",
  "This is the sweet taste of success. Savor it.",
  "You're a machine! Your work ethic is incredible.",
  "This achievement is a reflection of your inner strength.",
  "You're turning potential into performance. Amazing!",
  "This is a milestone worth celebrating. What's next on the map?",
  "You're proving that the sky is the limit. Keep soaring.",
  "This is the kind of win that fuels future victories.",
  "Your dedication is a silent testament to your character.",
  "You're not just reaching your goals, you're redefining them.",
  "This is a victory for focus, for effort, and for you.",
  "You've just made a deposit in the bank of your success.",
  "Your journey is inspiring. This is another highlight.",
  "You're a true professional. This achievement is top-tier."
];

export const getRandomMotivationalMessage = () => {
  return motivationalMessages[Math.floor(Math.random() * motivationalMessages.length)];
};
