
// src/worker/index.ts - Enhanced PWA Service Worker
/// <reference lib="webworker" />

// Cache version for update management
const CACHE_VERSION = 'v1.0.0';

import {precacheAndRoute} from 'workbox-precaching';
import {registerRoute} from 'workbox-routing';
import {CacheFirst, StaleWhileRevalidate, NetworkOnly, NetworkFirst} from 'workbox-strategies';
import {CacheableResponsePlugin} from 'workbox-cacheable-response';
import {ExpirationPlugin} from 'workbox-expiration';
import { RouteHandlerCallbackOptions } from 'workbox-core';
import { BackgroundSyncPlugin } from 'workbox-background-sync';

declare const self: ServiceWorkerGlobalScope;

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Cache tiering policy implementation
const CACHE_TIER = {
  EVERGREEN: {
    cacheName: 'evergreen-assets',
    strategy: 'CacheFirst',
    maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
    maxEntries: 100
  },
  STATIC: {
    cacheName: 'static-assets',
    strategy: 'CacheFirst',
    maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
    maxEntries: 200
  },
  PUBLICITY: {
    cacheName: 'publicity-assets',
    strategy: 'StaleWhileRevalidate',
    maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
    maxEntries: 60
  },
  AUDIO: {
    cacheName: 'audio-assets',
    strategy: 'CacheFirst',
    maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
    maxEntries: 20
  },
  API: {
    cacheName: 'api-data',
    strategy: 'StaleWhileRevalidate',
    maxAgeSeconds: 6 * 60 * 60 // 6 hours
  }
};

// Enhanced API caching with stale-while-revalidate
const SIX_HOURS_IN_SECONDS = 6 * 60 * 60;

const apiCacheHandler = async ({ request, url }: RouteHandlerCallbackOptions) => {
  const cache = await caches.open(CACHE_TIER.API.cacheName);

  const fetchAndCache = async () => {
    try {
      const networkResponse = await fetch(request);
      if (networkResponse.ok) {
        const responseToCache = networkResponse.clone();
        const headers = new Headers(responseToCache.headers);
        headers.set('x-sw-cache-timestamp', new Date().toISOString());
        
        const body = await responseToCache.blob();
        
        await cache.put(request, new Response(body, {
          status: responseToCache.status,
          statusText: responseToCache.statusText,
          headers: headers
        }));
      }
      return networkResponse;
    } catch (error) {
      console.error(`[SW] Network fetch for ${url.href} failed. Serving stale content if available.`, error);
      const cachedResponse = await cache.match(request);
      if (cachedResponse) {
        return cachedResponse;
      }
      throw error;
    }
  };

  const cachedResponse = await cache.match(request);

  if (cachedResponse) {
    const timestampHeader = cachedResponse.headers.get('x-sw-cache-timestamp');
    if (timestampHeader) {
      const cachedTime = new Date(timestampHeader).getTime();
      const now = new Date().getTime();
      const ageInSeconds = (now - cachedTime) / 1000;

      if (ageInSeconds < SIX_HOURS_IN_SECONDS) {
        return cachedResponse;
      }
    }
    return fetchAndCache();
  }

  return fetchAndCache();
};

// Register API caching route
registerRoute(
  ({url}) => url.pathname.startsWith('/api/'),
  apiCacheHandler
);

// Evergreen assets (fonts, icons, core images) - Cache First with long expiration
registerRoute(
  ({request}) => {
    return request.destination === 'font' || 
           request.destination === 'manifest' ||
           request.url.includes('/fonts/') ||
           request.url.includes('/icons/');
  },
  new CacheFirst({
    cacheName: CACHE_TIER.EVERGREEN.cacheName,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: CACHE_TIER.EVERGREEN.maxEntries,
        maxAgeSeconds: CACHE_TIER.EVERGREEN.maxAgeSeconds,
      }),
    ],
  })
);

// Offline resilience handler - provides fallbacks for missing assets
registerRoute(
  ({request}) => {
    // Handle icon requests with fallback
    if (request.url.includes('/icons/') && request.destination === 'image') {
      return true;
    }
    // Handle font requests with fallback
    if (request.url.includes('/fonts/') && request.destination === 'font') {
      return true;
    }
    return false;
  },
  async ({request, event}) => {
    const cache = await caches.open(CACHE_TIER.EVERGREEN.cacheName);
    const cached = await cache.match(request);
    
    if (cached) {
      return cached;
    }
    
    // If no cached version and we're offline, provide a fallback
    if (!navigator.onLine) {
      // For icons, return a default icon if available
      if (request.url.includes('/icons/')) {
        const fallbackIcon = await cache.match('/icons/icon-192x192.png');
        if (fallbackIcon) {
          return fallbackIcon;
        }
      }
      
      // For fonts, return a system font fallback
      if (request.url.includes('/fonts/')) {
        return new Response('', { status: 200 });
      }
    }
    
    // If we're online, try to fetch from network
    try {
      const response = await fetch(request);
      if (response.ok) {
        await cache.put(request, response.clone());
        return response;
      }
    } catch (error) {
      console.error(`Failed to fetch ${request.url}:`, error);
    }
    
    // Return a minimal fallback response
    return new Response('', { status: 200 });
  }
);

// Static images - Cache First
registerRoute(
  ({request}) => request.destination === 'image' && 
                !request.url.includes('actions.google.com') &&
                !request.url.includes('placehold.co'),
  new CacheFirst({
    cacheName: CACHE_TIER.STATIC.cacheName,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: CACHE_TIER.STATIC.maxEntries,
        maxAgeSeconds: CACHE_TIER.STATIC.maxAgeSeconds,
      }),
    ],
  })
);

// Publicity assets (CDN banners, external images) - Stale-While-Revalidate
registerRoute(
  ({request}) => request.destination === 'image' && 
                (request.url.includes('placehold.co') || 
                 request.url.includes('cdn') ||
                 request.url.includes('unsplash') ||
                 request.url.includes('images.unsplash')),
  new StaleWhileRevalidate({
    cacheName: CACHE_TIER.PUBLICITY.cacheName,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: CACHE_TIER.PUBLICITY.maxEntries,
        maxAgeSeconds: CACHE_TIER.PUBLICITY.maxAgeSeconds,
      }),
    ],
  })
);

// Audio files - Cache First
registerRoute(
  ({request}) => request.destination === 'audio' || 
                request.url.includes('actions.google.com'),
  new CacheFirst({
    cacheName: CACHE_TIER.AUDIO.cacheName,
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: CACHE_TIER.AUDIO.maxEntries,
        maxAgeSeconds: CACHE_TIER.AUDIO.maxAgeSeconds,
      }),
    ],
  })
);

// Page/Navigation caching - Cache First for app shell
registerRoute(
  ({request}) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'pages',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 24 * 60 * 60, // 24 hours
      }),
    ],
  })
);

// Offline fallback for navigation
registerRoute(
  ({url}) => url.pathname.startsWith('/briefing') || url.pathname.startsWith('/chat'),
  async ({request}) => {
    if (!navigator.onLine) {
      // Return offline fallback for AI routes
      const cache = await caches.open('offline-fallbacks');
      const offlineResponse = await cache.match('/offline.html');
      return offlineResponse || new Response('Offline', { status: 503 });
    }
    
    return fetch(request);
  }
);

// JavaScript and CSS files - Cache First
registerRoute(
  ({request}) => request.destination === 'script' || request.destination === 'style',
  new CacheFirst({
    cacheName: 'static-resources',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 1 week
      }),
    ],
  })
);

// Background sync for failed mutations
const bgSyncPlugin = new BackgroundSyncPlugin('api-mutation-queue', {
  maxRetentionTime: 24 * 60 // Retry for up to 24 hours
});

registerRoute(
  ({ url, request }) =>
    url.pathname.startsWith('/api/') &&
    ['POST', 'PUT', 'DELETE'].includes(request.method),
  new NetworkOnly({
    plugins: [bgSyncPlugin]
  })
);

// Service worker event handlers
self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data && event.data.type === 'HARD_REFRESH') {
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          return caches.delete(cacheName);
        })
      );
    });
  }
  if (event.data && event.data.type === 'CLEAR_CACHE') {
    // Clear specific cache tiers
    const { tier } = event.data;
    if (tier && CACHE_TIER[tier.toUpperCase()]) {
      caches.delete(CACHE_TIER[tier.toUpperCase()].cacheName);
    }
  }
});

// Handle service worker updates
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    self.clients.claim()
  );
  
  // Clean up old caches
  event.waitUntil(
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          if (cacheName.startsWith('evergreen-') || 
              cacheName.startsWith('static-') || 
              cacheName.startsWith('publicity-') ||
              cacheName.startsWith('audio-') ||
              cacheName.startsWith('api-')) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});


// ** Image Caching (Cache First) **
registerRoute(
  ({request}) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// ** Page/Navigation Caching (Cache First) **
// This ensures the app shell is always available from the cache first for instant navigation.
registerRoute(
  ({request}) => request.mode === 'navigate',
  new CacheFirst({
    cacheName: 'pages',
  })
);


self.addEventListener('message', (event: any) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data && event.data.type === 'HARD_REFRESH') {
    caches.keys().then(cacheNames => {
      return Promise.all(
        cacheNames.map(cacheName => {
          return caches.delete(cacheName);
        })
      );
    });
  }
});
