name: Capacitor Android APK

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Enable corepack
      run: corepack enable
    
    - name: Install dependencies
      run: npm ci
    
    # If you have a web build step (React/Vue/Angular) — uncomment this
    # - name: Build web assets
    #   run: npm run build
    
    - name: Capacitor sync (android)
      run: npx cap sync android
    
    - name: Debug - list generated folders
      run: |
        ls -la android
        ls -la android/capacitor-cordova-android-plugins || true
    
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Install Android SDK components & accept licenses
      run: |
        sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
        yes | sdkmanager --licenses
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    
    - name: Make gradlew executable
      working-directory: android
      run: chmod +x ./gradlew
    
    - name: Build release APK
      working-directory: android
      run: ./gradlew assembleRelease --stacktrace --info
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/*.apk
        retention-days: 30